### ISSUE TITLE
How to run it ?

### ISSUE THREAD

**Issue by wangshunping** [byteweaver/django-coupons#15]
I am not familiar to djingo.

My question is , when I git clone it from website, how can i run it ?

I have using python setup.py build and python setup.py install

**Comment by wangshunping** [comment]
```
(venv)guo@pingdeMacBook-Air-2 coupons$ pwd
/Users/guo/Code/repository/02.Learn/00.python_learn/django-coupons/build/lib/coupons
(venv)guo@pingdeMacBook-Air-2 coupons$ l
total 48
-rw-r--r--  1 guo  staff    22B  1  4 16:50 __init__.py
-rw-r--r--  1 guo  staff   2.7K  1  4 16:50 admin.py
-rw-r--r--  1 guo  staff   1.9K  1  4 16:50 forms.py
drwxr-xr-x  3 guo  staff   102B  1  4 16:51 locale
drwxr-xr-x  6 guo  staff   204B  1  4 16:51 migrations
-rw-r--r--  1 guo  staff   4.0K  1  4 16:50 models.py
-rw-r--r--  1 guo  staff   598B  1  4 16:50 settings.py
drwxr-xr-x  6 guo  staff   204B  1  4 16:51 south_migrations
drwxr-xr-x  3 guo  staff   102B  1  4 16:51 templates
drwxr-xr-x  7 guo  staff   238B  1  4 16:51 tests
(venv)guo@pingdeMacBook-Air-2 coupons$ python admin.py runserver
Traceback (most recent call last):
  File "admin.py", line 2, in <module>
    from django.contrib import admin
  File "/Users/guo/Code/repository/01.Work/grid-cdnzz/venv/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 4, in <module>
    from django.contrib.admin.helpers import ACTION_CHECKBOX_NAME
  File "/Users/guo/Code/repository/01.Work/grid-cdnzz/venv/lib/python2.7/site-packages/django/contrib/admin/helpers.py", line 8, in <module>
    from django.contrib.admin.utils import (
  File "/Users/guo/Code/repository/01.Work/grid-cdnzz/venv/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 7, in <module>
    from django.contrib.auth import get_permission_codename
  File "/Users/guo/Code/repository/01.Work/grid-cdnzz/venv/lib/python2.7/site-packages/django/contrib/auth/__init__.py", line 7, in <module>
    from django.middleware.csrf import rotate_token
  File "/Users/guo/Code/repository/01.Work/grid-cdnzz/venv/lib/python2.7/site-packages/django/middleware/csrf.py", line 14, in <module>
    from django.utils.cache import patch_vary_headers
  File "/Users/guo/Code/repository/01.Work/grid-cdnzz/venv/lib/python2.7/site-packages/django/utils/cache.py", line 26, in <module>
    from django.core.cache import caches
  File "/Users/guo/Code/repository/01.Work/grid-cdnzz/venv/lib/python2.7/site-packages/django/core/cache/__init__.py", line 34, in <module>
    if DEFAULT_CACHE_ALIAS not in settings.CACHES:
  File "/Users/guo/Code/repository/01.Work/grid-cdnzz/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 48, in __getattr__
    self._setup(name)
  File "/Users/guo/Code/repository/01.Work/grid-cdnzz/venv/lib/python2.7/site-packages/django/conf/__init__.py", line 42, in _setup
    % (desc, ENVIRONMENT_VARIABLE))
django.core.exceptions.ImproperlyConfigured: Requested setting CACHES, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
```

**Comment by noxan** [comment]
I would recommend you to start with the official Django tutorial first: https://docs.djangoproject.com/en/1.9/intro/tutorial01/

Considering your question: this is just a pluggable application which can be run within a Django project but not standalone. You could follow the first steps of the tutorial and then have a look at the readme file of this project on how to run it.

I will close this ticket since it is not really related to this project. You should get familiar with Django first, if there are any questions then, on how to run this application, fee free to reopen the ticket. Good luck! :)
